### ISSUE TITLE
errors build with SDL3 3.1.6

### ISSUE THREAD

**Issue by SergeyDjam** [atsb/Doom64EX-Plus#285]
```
src/engine/i_audio.c: In function 'Signal_StopAll':
src/engine/i_audio.c:105:32: error: void value not ignored as it ought to be
 #define SEMAPHORE_LOCK()    if(SDL_WaitSemaphore(semaphore) == 0) {
                                ^
src/engine/i_audio.c:733:5: note: in expansion of macro 'SEMAPHORE_LOCK'
     SEMAPHORE_LOCK()
     ^
src/engine/i_audio.c: In function 'Signal_Pause':
src/engine/i_audio.c:105:32: error: void value not ignored as it ought to be
 #define SEMAPHORE_LOCK()    if(SDL_WaitSemaphore(semaphore) == 0) {
                                ^
src/engine/i_audio.c:768:5: note: in expansion of macro 'SEMAPHORE_LOCK'
     SEMAPHORE_LOCK()
     ^
src/engine/i_audio.c: In function 'Signal_Resume':
src/engine/i_audio.c:105:32: error: void value not ignored as it ought to be
 #define SEMAPHORE_LOCK()    if(SDL_WaitSemaphore(semaphore) == 0) {
                                ^
src/engine/i_audio.c:788:5: note: in expansion of macro 'SEMAPHORE_LOCK'
     SEMAPHORE_LOCK()
     ^
src/engine/i_audio.c: In function 'Signal_UpdateGain':
src/engine/i_audio.c:105:32: error: void value not ignored as it ought to be
 #define SEMAPHORE_LOCK()    if(SDL_WaitSemaphore(semaphore) == 0) {
                                ^
src/engine/i_audio.c:803:5: note: in expansion of macro 'SEMAPHORE_LOCK'
     SEMAPHORE_LOCK()
     ^
src/engine/i_audio.c: In function 'Seq_RunSong':
src/engine/i_audio.c:105:32: error: void value not ignored as it ought to be
 #define SEMAPHORE_LOCK()    if(SDL_WaitSemaphore(semaphore) == 0) {
                                ^
src/engine/i_audio.c:959:5: note: in expansion of macro 'SEMAPHORE_LOCK'
     SEMAPHORE_LOCK()
     ^
src/engine/i_audio.c: In function 'I_StartMusic':
src/engine/i_audio.c:105:32: error: void value not ignored as it ought to be
 #define SEMAPHORE_LOCK()    if(SDL_WaitSemaphore(semaphore) == 0) {
                                ^
src/engine/i_audio.c:1437:5: note: in expansion of macro 'SEMAPHORE_LOCK'
     SEMAPHORE_LOCK()
     ^
src/engine/i_audio.c: In function 'I_StopSound':
src/engine/i_audio.c:105:32: error: void value not ignored as it ought to be
 #define SEMAPHORE_LOCK()    if(SDL_WaitSemaphore(semaphore) == 0) {
                                ^
src/engine/i_audio.c:1469:5: note: in expansion of macro 'SEMAPHORE_LOCK'
     SEMAPHORE_LOCK()
     ^
src/engine/i_audio.c: In function 'I_StartSound':
src/engine/i_audio.c:105:32: error: void value not ignored as it ought to be
 #define SEMAPHORE_LOCK()    if(SDL_WaitSemaphore(semaphore) == 0) {
                                ^
src/engine/i_audio.c:1498:5: note: in expansion of macro 'SEMAPHORE_LOCK'
     SEMAPHORE_LOCK()
     ^
gcc  -I/usr/include/libpng16 -I/usr/include/libdrm -I/usr/include/libdrm    -c -o src/engine/w_wad.o src/engine/w_wad.c
make: *** [<builtin>: src/engine/i_audio.o] Error 1
```

what fix it? 
LINUX ROSA R11
SDL3 3.1.6
GCC 5.5.0
[Doom64EX-Plus](https://github.com/atsb/Doom64EX-Plus) 4.0.0.3

**Comment by atsb** [comment]
It currently builds with 3.1.3 only, 3.1.6 isn't supported yet.

**Comment by SergeyDjam** [comment]
```
src/engine/i_audio.c: In function 'Signal_StopAll':
src/engine/i_audio.c:105:32: error: void value not ignored as it ought to be
 #define SEMAPHORE_LOCK()    if(SDL_WaitSemaphore(semaphore) == 0) {
                                ^
src/engine/i_audio.c:733:5: note: in expansion of macro 'SEMAPHORE_LOCK'
     SEMAPHORE_LOCK()
     ^
src/engine/i_audio.c: In function 'Signal_Pause':
src/engine/i_audio.c:105:32: error: void value not ignored as it ought to be
 #define SEMAPHORE_LOCK()    if(SDL_WaitSemaphore(semaphore) == 0) {
                                ^
src/engine/i_audio.c:768:5: note: in expansion of macro 'SEMAPHORE_LOCK'
     SEMAPHORE_LOCK()
     ^
src/engine/i_audio.c: In function 'Signal_Resume':
src/engine/i_audio.c:105:32: error: void value not ignored as it ought to be
 #define SEMAPHORE_LOCK()    if(SDL_WaitSemaphore(semaphore) == 0) {
                                ^
src/engine/i_audio.c:788:5: note: in expansion of macro 'SEMAPHORE_LOCK'
     SEMAPHORE_LOCK()
     ^
src/engine/i_audio.c: In function 'Signal_UpdateGain':
src/engine/i_audio.c:105:32: error: void value not ignored as it ought to be
 #define SEMAPHORE_LOCK()    if(SDL_WaitSemaphore(semaphore) == 0) {
                                ^
src/engine/i_audio.c:803:5: note: in expansion of macro 'SEMAPHORE_LOCK'
     SEMAPHORE_LOCK()
     ^
src/engine/i_audio.c: In function 'Seq_RunSong':
src/engine/i_audio.c:105:32: error: void value not ignored as it ought to be
 #define SEMAPHORE_LOCK()    if(SDL_WaitSemaphore(semaphore) == 0) {
                                ^
src/engine/i_audio.c:959:5: note: in expansion of macro 'SEMAPHORE_LOCK'
     SEMAPHORE_LOCK()
     ^
src/engine/i_audio.c: In function 'I_StartMusic':
src/engine/i_audio.c:105:32: error: void value not ignored as it ought to be
 #define SEMAPHORE_LOCK()    if(SDL_WaitSemaphore(semaphore) == 0) {
                                ^
src/engine/i_audio.c:1437:5: note: in expansion of macro 'SEMAPHORE_LOCK'
     SEMAPHORE_LOCK()
     ^
src/engine/i_audio.c: In function 'I_StopSound':
src/engine/i_audio.c:105:32: error: void value not ignored as it ought to be
 #define SEMAPHORE_LOCK()    if(SDL_WaitSemaphore(semaphore) == 0) {
                                ^
src/engine/i_audio.c:1469:5: note: in expansion of macro 'SEMAPHORE_LOCK'
     SEMAPHORE_LOCK()
     ^
src/engine/i_audio.c: In function 'I_StartSound':
src/engine/i_audio.c:105:32: error: void value not ignored as it ought to be
 #define SEMAPHORE_LOCK()    if(SDL_WaitSemaphore(semaphore) == 0) {
                                ^
src/engine/i_audio.c:1498:5: note: in expansion of macro 'SEMAPHORE_LOCK'
     SEMAPHORE_LOCK()
     ^
make: *** [<builtin>: src/engine/i_audio.o] Error 1
make: *** Waiting for unfinished jobs....

```
SDL3 3.1.3

**Comment by SergeyDjam** [comment]
```
/opt/llvm17/bin/clang -I/usr/include/libstdc++-gcc10 -I/usr/include/libstdc++-gcc10/x86_64-unknown-linux-gnu   -c -o src/engine/net_query.o src/engine/net_query.c
src/engine/net_client.c:1279:19: warning: implicit conversion from enumeration type 'net_connstate_t' to different enumeration type 'net_clientstate_t' [-Wenum-conversion]
 1279 |                         client_state = NET_CONN_STATE_DISCONNECTED;
      |                                      ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/engine/net_client.c:1304:15: warning: passing 'int8_t *' (aka 'signed char *') to parameter of type 'char *' converts between pointers to integer types where one is of the unique plain 'char' type and the other is not [-Wpointer-sign]
 1304 |                 CON_CvarSet(m_playername.name, myargv[p + 1]);
      |                             ^~~~~~~~~~~~~~~~~
src/engine/con_cvar.h:86:24: note: passing argument to parameter 'var_name' here
   86 | void CON_CvarSet(char *var_name, char *value);
      |                        ^
src/engine/net_client.c:1307:19: warning: assigning to 'char *' from 'int8_t *' (aka 'signed char *') converts between pointers to integer types where one is of the unique plain 'char' type and the other is not [-Wpointer-sign]
 1307 |                 net_player_name = m_playername.string;
      |                                 ^ ~~~~~~~~~~~~~~~~~~~
src/engine/m_menu.c:4128:8: error: call to undeclared function 'I_JoystickToKey'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 4128 |                 ch = I_JoystickToKey(ev->data1);
      |                      ^

```
SDL3 3.1.3
clang17

**Comment by SergeyDjam** [comment]
```
-- SDL3 was configured with the following options:
-- 
-- Platform: Linux-5.13.9-generic-1rosa-x86_64
-- 64-bit:   TRUE
-- Compiler: /usr/bin/cc
-- Revision: SDL-3.1.3
-- Vendor:   
-- 
-- Subsystems:
--   Audio:    ON
--   Video:    ON
--   GPU:      ON
--   Render:   ON
--   Camera:   ON
--   Joystick: ON
--   Haptic:   ON
--   Hidapi:   ON
--   Power:    ON
--   Sensor:   ON
--   Dialog:   ON
-- 
-- Options:
--   SDL_ALSA                    (Wanted: ON): ON
--   SDL_ALSA_SHARED             (Wanted: ON): ON
--   SDL_ALTIVEC                 (Wanted: OFF): OFF
--   SDL_ARMNEON                 (Wanted: OFF): OFF
--   SDL_ARMSIMD                 (Wanted: OFF): OFF
--   SDL_ASAN                    (Wanted: OFF): OFF
--   SDL_ASSEMBLY                (Wanted: ON): ON
--   SDL_ASSERTIONS              (Wanted: auto): auto
--   SDL_AVX                     (Wanted: ON): ON
--   SDL_AVX2                    (Wanted: ON): ON
--   SDL_AVX512F                 (Wanted: ON): ON
--   SDL_BACKGROUNDING_SIGNAL    (Wanted: OFF): OFF
--   SDL_CCACHE                  (Wanted: OFF): OFF
--   SDL_CLANG_TIDY              (Wanted: OFF): OFF
--   SDL_CLOCK_GETTIME           (Wanted: ON): ON
--   SDL_COCOA                   (Wanted: OFF): OFF
--   SDL_DBUS                    (Wanted: ON): ON
--   SDL_DIRECTX                 (Wanted: OFF): OFF
--   SDL_DISABLE_INSTALL         (Wanted: OFF): OFF
--   SDL_DISABLE_UNINSTALL       (Wanted: OFF): OFF
--   SDL_DISKAUDIO               (Wanted: ON): ON
--   SDL_DUMMYAUDIO              (Wanted: ON): ON
--   SDL_DUMMYCAMERA             (Wanted: ON): ON
--   SDL_DUMMYVIDEO              (Wanted: ON): ON
--   SDL_EXAMPLES                (Wanted: OFF): OFF
--   SDL_EXAMPLES_LINK_SHARED    (Wanted: ON): OFF
--   SDL_FOREGROUNDING_SIGNAL    (Wanted: OFF): OFF
--   SDL_GCC_ATOMICS             (Wanted: ON): ON
--   SDL_GPU_DXVK                (Wanted: OFF): OFF
--   SDL_HIDAPI                  (Wanted: ON): ON
--   SDL_HIDAPI_JOYSTICK         (Wanted: ON): ON
--   SDL_HIDAPI_LIBUSB           (Wanted: ON): ON
--   SDL_HIDAPI_LIBUSB_SHARED    (Wanted: ON): ON
--   SDL_IBUS                    (Wanted: ON): OFF
--   SDL_INSTALL_TESTS           (Wanted: OFF): OFF
--   SDL_JACK                    (Wanted: ON): ON
--   SDL_JACK_SHARED             (Wanted: ON): ON
--   SDL_KMSDRM                  (Wanted: ON): ON
--   SDL_KMSDRM_SHARED           (Wanted: ON): ON
--   SDL_LASX                    (Wanted: OFF): OFF
--   SDL_LIBC                    (Wanted: ON): ON
--   SDL_LIBICONV                (Wanted: OFF): OFF
--   SDL_LIBUDEV                 (Wanted: ON): ON
--   SDL_LSX                     (Wanted: OFF): OFF
--   SDL_METAL                   (Wanted: OFF): OFF
--   SDL_MMX                     (Wanted: ON): ON
--   SDL_OFFSCREEN               (Wanted: ON): ON
--   SDL_OPENGL                  (Wanted: ON): ON
--   SDL_OPENGLES                (Wanted: ON): ON
--   SDL_OSS                     (Wanted: OFF): OFF
--   SDL_PIPEWIRE                (Wanted: ON): OFF
--   SDL_PIPEWIRE_SHARED         (Wanted: ON): OFF
--   SDL_PTHREADS                (Wanted: ON): ON
--   SDL_PTHREADS_SEM            (Wanted: ON): ON
--   SDL_PULSEAUDIO              (Wanted: ON): ON
--   SDL_PULSEAUDIO_SHARED       (Wanted: ON): ON
--   SDL_RENDER_D3D              (Wanted: OFF): OFF
--   SDL_RENDER_D3D11            (Wanted: OFF): OFF
--   SDL_RENDER_D3D12            (Wanted: OFF): OFF
--   SDL_RENDER_GPU              (Wanted: ON): ON
--   SDL_RENDER_METAL            (Wanted: ON): OFF
--   SDL_RENDER_VULKAN           (Wanted: ON): ON
--   SDL_ROCKCHIP                (Wanted: OFF): OFF
--   SDL_RPATH                   (Wanted: ON): ON
--   SDL_RPI                     (Wanted: OFF): OFF
--   SDL_SNDIO                   (Wanted: ON): ON
--   SDL_SNDIO_SHARED            (Wanted: ON): ON
--   SDL_SSE                     (Wanted: ON): ON
--   SDL_SSE2                    (Wanted: ON): ON
--   SDL_SSE3                    (Wanted: ON): ON
--   SDL_SSE4_1                  (Wanted: ON): ON
--   SDL_SSE4_2                  (Wanted: ON): ON
--   SDL_SYSTEM_ICONV            (Wanted: ON): ON
--   SDL_TESTS                   (Wanted: OFF): OFF
--   SDL_TESTS_LINK_SHARED       (Wanted: ON): OFF
--   SDL_VIRTUAL_JOYSTICK        (Wanted: ON): ON
--   SDL_VIVANTE                 (Wanted: OFF): OFF
--   SDL_VULKAN                  (Wanted: ON): ON
--   SDL_WASAPI                  (Wanted: OFF): OFF
--   SDL_WAYLAND                 (Wanted: ON): OFF
--   SDL_WAYLAND_LIBDECOR        (Wanted: ON): OFF
--   SDL_WAYLAND_LIBDECOR_SHARED (Wanted: ON): OFF
--   SDL_WAYLAND_SHARED          (Wanted: ON): OFF
--   SDL_X11                     (Wanted: ON): ON
--   SDL_X11_SHARED              (Wanted: ON): ON
--   SDL_X11_XCURSOR             (Wanted: ON): ON
--   SDL_X11_XDBE                (Wanted: ON): ON
--   SDL_X11_XFIXES              (Wanted: ON): ON
--   SDL_X11_XINPUT              (Wanted: ON): ON
--   SDL_X11_XRANDR              (Wanted: ON): ON
--   SDL_X11_XSCRNSAVER          (Wanted: ON): ON
--   SDL_X11_XSHAPE              (Wanted: ON): ON
--   SDL_XINPUT                  (Wanted: OFF): OFF
-- 
--  Build Shared Library: ON
--  Build Static Library: OFF
-- 
```

**Comment by atsb** [comment]
Just updated to 3.1.8 on Windows and it required zero changes at all.
